2025-02-28 19:24:58,754 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:24:58,765 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:24:58,765 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:24:58,765 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:24:58,765 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:24:58,765 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:24:58,766 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:24:58,767 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:24:58,767 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:24:58,767 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:24:58,767 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:24:58,767 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:24:58,767 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:24:58,767 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] result = await self._request_wrapper(
2025-02-28 19:24:58,768 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
2025-02-28 19:24:58,769 - root - INFO - [Telegram Bot] raise Conflict(message)
2025-02-28 19:24:58,769 - root - INFO - [Telegram Bot] telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:24:59,134 - root - INFO - [Flask App] Starting Flask application on port 10000...
2025-02-28 19:24:59,134 - root - INFO - [Flask App] 2025-02-28 19:24:59,133 - app - INFO - [API] ÿ·» ÃœÌœ ·‹ /api/submit_kyc - IP: 127.0.0.1, RequestID: u7iek2blse942nnf
2025-02-28 19:24:59,135 - root - INFO - [Flask App] 2025-02-28 19:24:59,133 - app - INFO - [API] ÿ·» ÃœÌœ ·‹ /api/submit_kyc - IP: 127.0.0.1, RequestID: u7iek2blse942nnf
2025-02-28 19:24:59,138 - root - INFO - [Flask App] 2025-02-28 19:24:59,138 - app - INFO - Ã«—Ì —›⁄ «·’Ê—… ≈·Ï Cloudinary... („Õ«Ê·… 1/3)
2025-02-28 19:24:59,138 - root - INFO - [Flask App] 2025-02-28 19:24:59,138 - app - INFO - Ã«—Ì —›⁄ «·’Ê—… ≈·Ï Cloudinary... („Õ«Ê·… 1/3)
2025-02-28 19:25:01,090 - root - INFO - [Flask App] 2025-02-28 19:25:01,090 - app - INFO -  „ —›⁄ «·’Ê—… »‰Ã«Õ: kyc_photos/kvxlzszp2qxlvhpb6z78
2025-02-28 19:25:01,091 - root - INFO - [Flask App] 2025-02-28 19:25:01,090 - app - INFO -  „ —›⁄ «·’Ê—… »‰Ã«Õ: kyc_photos/kvxlzszp2qxlvhpb6z78
2025-02-28 19:25:01,092 - root - INFO - [Flask App] 2025-02-28 19:25:01,092 - app - INFO - Ã«—Ì —›⁄ «·’Ê—… ≈·Ï Cloudinary... („Õ«Ê·… 1/3)
2025-02-28 19:25:01,094 - root - INFO - [Flask App] 2025-02-28 19:25:01,092 - app - INFO - Ã«—Ì —›⁄ «·’Ê—… ≈·Ï Cloudinary... („Õ«Ê·… 1/3)
2025-02-28 19:25:01,783 - root - INFO - [Flask App] 2025-02-28 19:25:01,781 - app - INFO -  „ —›⁄ «·’Ê—… »‰Ã«Õ: kyc_photos/zecslhaqmi3wz15jpmic
2025-02-28 19:25:01,783 - root - INFO - [Flask App] 2025-02-28 19:25:01,781 - app - INFO -  „ —›⁄ «·’Ê—… »‰Ã«Õ: kyc_photos/zecslhaqmi3wz15jpmic
2025-02-28 19:25:05,003 - root - INFO - [Flask App] 2025-02-28 19:25:05,003 - database - WARNING - ⁄„Êœ welcome_message_id €Ì— „ÊÃÊœ ›Ì ÃœÊ· kyc_application.  „  Ã«Â·Â ›Ì «·≈œ—«Ã.
2025-02-28 19:25:05,267 - root - INFO - [Flask App] 2025-02-28 19:25:05,267 - database - INFO -  „ Õ›Ÿ ÿ·» «· Õﬁﬁ „‰ «·ÂÊÌ… »—ﬁ„ KYC-20250228-FAB6XQII
2025-02-28 19:25:05,927 - root - INFO - [Flask App] 2025-02-28 19:25:05,926 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/sendMessage "HTTP/1.1 200 OK"
2025-02-28 19:25:05,928 - root - INFO - [Flask App] 2025-02-28 19:25:05,928 - telegram_notifier - INFO -  „ ≈—”«· ≈‘⁄«— »ÿ·» KYC ÃœÌœ ≈·Ï „Ã„Ê⁄… «·„‘—›Ì‰
2025-02-28 19:25:05,932 - root - INFO - [Flask App] 2025-02-28 19:25:05,932 - app - INFO - [API]  „ ≈—”«· ÿ·» «· ÊÀÌﬁ »‰Ã«Õ - IP: 127.0.0.1, RequestID: u7iek2blse942nnf, ApplicationID: KYC-20250228-FAB6XQII
2025-02-28 19:25:05,932 - root - INFO - [Flask App] 2025-02-28 19:25:05,932 - app - INFO - [API]  „ ≈—”«· ÿ·» «· ÊÀÌﬁ »‰Ã«Õ - IP: 127.0.0.1, RequestID: u7iek2blse942nnf, ApplicationID: KYC-20250228-FAB6XQII
2025-02-28 19:25:05,933 - root - INFO - [Flask App] 2025-02-28 19:25:05,932 - werkzeug - INFO - 127.0.0.1 - - [28/Feb/2025 19:25:05] "POST /api/submit_kyc HTTP/1.1" 200 -
2025-02-28 19:25:14,710 - root - INFO - [Telegram Bot] 2025-02-28 19:25:14,709 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 200 OK"
2025-02-28 19:25:15,248 - root - INFO - [Telegram Bot] 2025-02-28 19:25:15,248 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/answerCallbackQuery "HTTP/1.1 200 OK"
2025-02-28 19:25:15,461 - root - INFO - [Telegram Bot] 2025-02-28 19:25:15,460 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/editMessageText "HTTP/1.1 200 OK"
2025-02-28 19:25:16,464 - root - INFO - [Telegram Bot] 2025-02-28 19:25:16,464 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 200 OK"
2025-02-28 19:25:16,466 - root - INFO - [Telegram Bot] 2025-02-28 19:25:16,466 - __main__ - INFO - \u2705 „⁄«·Ã… —”«·… „‰ „Ã„Ê⁄… «·„‘—›Ì‰ («·„” Œœ„: 6648998922)
2025-02-28 19:25:16,466 - root - INFO - [Telegram Bot] 2025-02-28 19:25:16,466 - __main__ - INFO - \U0001f504 ≈ﬂ„«· ≈Ã—«¡ «·„‘—›: approve ··ÿ·» KYC-20250228-FAB6XQII »„Õ ÊÏ: 111
2025-02-28 19:25:19,421 - root - INFO - [Telegram Bot] 2025-02-28 19:25:19,419 - database - INFO -  „  «·„Ê«›ﬁ… ⁄·Ï «·ÿ·» KYC-20250228-FAB6XQII »Ê«”ÿ… Saper Ltd
2025-02-28 19:25:23,731 - root - INFO - [Telegram Bot] 2025-02-28 19:25:23,731 - telegram_notifier - WARNING - ·« ÌÊÃœ „⁄—›  ·€—«„ ··„” Œœ„ ’«Õ» «·ÿ·» KYC-20250228-FAB6XQII
2025-02-28 19:25:24,429 - root - INFO - [Telegram Bot] 2025-02-28 19:25:24,429 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/sendMessage "HTTP/1.1 200 OK"
2025-02-28 19:25:27,696 - root - INFO - [Telegram Bot] 2025-02-28 19:25:27,696 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/editMessageText "HTTP/1.1 200 OK"
2025-02-28 19:25:27,988 - root - INFO - [Telegram Bot] 2025-02-28 19:25:27,987 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 409 Conflict"
2025-02-28 19:25:27,988 - root - INFO - [Telegram Bot] 2025-02-28 19:25:27,988 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:25:27,988 - root - INFO - [Telegram Bot] 2025-02-28 19:25:27,988 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
2025-02-28 19:25:27,989 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:25:27,989 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:25:27,989 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:25:27,989 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:25:27,989 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:25:27,989 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:25:27,990 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:25:27,990 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:25:27,990 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:25:27,990 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:25:27,990 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:25:27,990 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:25:27,991 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:25:27,991 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:25:27,991 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:25:27,991 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
