2025-02-28 19:15:51,243 - root - INFO - [Flask App] 2025-02-28 19:15:51,242 - werkzeug - INFO -  * Detected change in 'C:\\Python310\\Lib\\logging\\handlers.py', reloading
2025-02-28 19:15:51,251 - root - INFO - [Flask App] 2025-02-28 19:15:51,251 - werkzeug - INFO -  * Detected change in 'C:\\Python310\\Lib\\threading.py', reloading
2025-02-28 19:15:51,251 - root - INFO - [Telegram Bot] return loop.run_until_complete(main)
2025-02-28 19:15:51,251 - root - INFO - [Telegram Bot] File "C:\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
2025-02-28 19:15:51,251 - root - INFO - [Telegram Bot] self.run_forever()
2025-02-28 19:15:51,251 - root - INFO - [Telegram Bot] File "C:\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] super().run_forever()
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] File "C:\Python310\lib\asyncio\base_events.py", line 595, in run_forever
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] self._run_once()
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] File "C:\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] handle._run()
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] File "C:\Python310\lib\asyncio\events.py", line 80, in _run
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] self._context.run(self._callback, *self._args)
2025-02-28 19:15:51,252 - root - INFO - [Telegram Bot] File "C:\Users\PC\CascadeProjects\kyc-web-app\main.py", line 1009, in run_fastapi
2025-02-28 19:15:51,253 - root - INFO - [Telegram Bot] await server.serve()
2025-02-28 19:15:51,253 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\uvicorn\server.py", line 78, in serve
2025-02-28 19:15:51,253 - root - INFO - [Telegram Bot] await self.startup(sockets=sockets)
2025-02-28 19:15:51,253 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\uvicorn\server.py", line 170, in startup
2025-02-28 19:15:51,253 - root - INFO - [Telegram Bot] sys.exit(1)
2025-02-28 19:15:51,253 - root - INFO - [Telegram Bot] SystemExit: 1
2025-02-28 19:15:51,278 - root - ERROR - Telegram Bot exited with code 1
2025-02-28 19:15:51,875 - root - INFO - [Flask App] Starting Flask application on port 10000...
2025-02-28 19:15:52,006 - root - INFO - [Flask App] 2025-02-28 19:15:52,006 - werkzeug - INFO -  * Restarting with watchdog (windowsapi)
2025-02-28 19:15:52,571 - root - INFO - [Flask App] Starting Flask application on port 10000...
2025-02-28 19:15:52,571 - root - INFO - [Flask App] * Serving Flask app 'app'
2025-02-28 19:15:52,572 - root - INFO - [Flask App] * Debug mode: on
2025-02-28 19:15:52,639 - root - INFO - [Flask App] 2025-02-28 19:15:52,639 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:15:52,639 - root - INFO - [Flask App] 2025-02-28 19:15:52,639 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:15:53,475 - root - INFO - [Flask App] 2025-02-28 19:15:53,475 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
2025-02-28 19:15:53,475 - root - INFO - [Flask App] * Running on all addresses (0.0.0.0)
2025-02-28 19:15:53,475 - root - INFO - [Flask App] * Running on http://127.0.0.1:10000
2025-02-28 19:15:53,476 - root - INFO - [Flask App] * Running on http://192.168.4.244:10000
2025-02-28 19:15:53,476 - root - INFO - [Flask App] 2025-02-28 19:15:53,475 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-02-28 19:15:53,480 - root - INFO - [Flask App] 2025-02-28 19:15:53,480 - werkzeug - INFO -  * Restarting with watchdog (windowsapi)
2025-02-28 19:15:54,111 - root - INFO - [Flask App] 2025-02-28 19:15:54,111 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:15:54,111 - root - INFO - [Flask App] 2025-02-28 19:15:54,111 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:15:56,800 - root - INFO - [Telegram Bot] 2025-02-28 19:15:56,799 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 200 OK"
2025-02-28 19:15:58,023 - root - INFO - [Flask App] 2025-02-28 19:15:58,023 - werkzeug - WARNING -  * Debugger is active!
2025-02-28 19:15:58,028 - root - INFO - [Flask App] 2025-02-28 19:15:58,027 - werkzeug - INFO -  * Debugger PIN: 535-157-907
2025-02-28 19:15:59,120 - root - INFO - [Flask App] 2025-02-28 19:15:59,120 - werkzeug - WARNING -  * Debugger is active!
2025-02-28 19:15:59,124 - root - INFO - [Flask App] 2025-02-28 19:15:59,123 - werkzeug - INFO -  * Debugger PIN: 535-157-907
2025-02-28 19:16:06,923 - root - INFO - [Telegram Bot] 2025-02-28 19:16:06,922 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 200 OK"
2025-02-28 19:16:10,141 - root - INFO - [Telegram Bot] 2025-02-28 19:16:10,141 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 409 Conflict"
2025-02-28 19:16:10,142 - root - INFO - [Telegram Bot] 2025-02-28 19:16:10,142 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:16:10,142 - root - INFO - [Telegram Bot] 2025-02-28 19:16:10,142 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
2025-02-28 19:16:10,142 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:16:10,143 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:16:10,144 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:16:10,144 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:16:10,144 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:16:10,144 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:16:10,146 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:16:10,146 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:16:10,147 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:16:10,147 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:16:10,148 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:16:10,148 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:16:10,149 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:16:10,149 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:16:10,149 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:16:10,150 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:16:10,150 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:16:10,150 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:16:10,150 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:16:10,150 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
2025-02-28 19:16:10,151 - root - INFO - [Telegram Bot] result = await self._request_wrapper(
2025-02-28 19:16:10,151 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
2025-02-28 19:16:10,152 - root - INFO - [Telegram Bot] raise Conflict(message)
2025-02-28 19:16:10,152 - root - INFO - [Telegram Bot] telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:16:21,269 - root - INFO - [Telegram Bot] 2025-02-28 19:16:21,268 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 200 OK"
2025-02-28 19:16:31,381 - root - INFO - [Telegram Bot] 2025-02-28 19:16:31,381 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 200 OK"
2025-02-28 19:24:06,501 - root - INFO - === Starting MetaBit KYC System ===
2025-02-28 19:24:06,501 - root - INFO - Starting Flask App...
2025-02-28 19:24:07,132 - root - INFO - [Flask App] 2025-02-28 19:24:07,131 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:24:07,132 - root - INFO - [Flask App] 2025-02-28 19:24:07,131 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:24:08,501 - root - INFO - Starting Telegram Bot...
2025-02-28 19:24:09,172 - root - INFO - [Telegram Bot] 2025-02-28 19:24:09,172 - __main__ - INFO - Bot Token: 80683...
2025-02-28 19:24:09,172 - root - INFO - [Telegram Bot] 2025-02-28 19:24:09,172 - __main__ - INFO - Admin Group ID: -1002484172002
2025-02-28 19:24:11,841 - root - INFO - [Telegram Bot] INFO:     Started server process [28532]
2025-02-28 19:24:11,841 - root - INFO - [Telegram Bot] INFO:     Waiting for application startup.
2025-02-28 19:24:11,841 - root - INFO - [Telegram Bot] INFO:     Application startup complete.
2025-02-28 19:24:11,844 - root - INFO - [Telegram Bot] INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
2025-02-28 19:24:12,430 - root - INFO - [Telegram Bot] 2025-02-28 19:24:12,430 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getMe "HTTP/1.1 200 OK"
