2025-02-28 19:24:30,035 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:24:30,046 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:24:30,046 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:24:30,046 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:24:30,046 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:24:30,046 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:24:30,047 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:24:30,047 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:24:30,047 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:24:30,047 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:24:30,047 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:24:30,048 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
2025-02-28 19:24:30,049 - root - INFO - [Telegram Bot] result = await self._request_wrapper(
2025-02-28 19:24:30,049 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
2025-02-28 19:24:30,049 - root - INFO - [Telegram Bot] raise Conflict(message)
2025-02-28 19:24:30,049 - root - INFO - [Telegram Bot] telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:24:35,940 - root - INFO - [Telegram Bot] 2025-02-28 19:24:35,940 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 409 Conflict"
2025-02-28 19:24:35,941 - root - INFO - [Telegram Bot] 2025-02-28 19:24:35,941 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:24:35,941 - root - INFO - [Telegram Bot] 2025-02-28 19:24:35,941 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
2025-02-28 19:24:35,942 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:24:35,942 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:24:35,944 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:24:35,944 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:24:35,944 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:24:35,945 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:24:35,945 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:24:35,946 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:24:35,946 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:24:35,946 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:24:35,947 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:24:35,948 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:24:35,948 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:24:35,949 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:24:35,949 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:24:35,949 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:24:35,950 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:24:35,951 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:24:35,951 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:24:35,952 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
2025-02-28 19:24:35,952 - root - INFO - [Telegram Bot] result = await self._request_wrapper(
2025-02-28 19:24:35,953 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
2025-02-28 19:24:35,953 - root - INFO - [Telegram Bot] raise Conflict(message)
2025-02-28 19:24:35,954 - root - INFO - [Telegram Bot] telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:24:45,030 - root - INFO - [Telegram Bot] 2025-02-28 19:24:45,029 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 409 Conflict"
2025-02-28 19:24:45,031 - root - INFO - [Telegram Bot] 2025-02-28 19:24:45,031 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:24:45,033 - root - INFO - [Telegram Bot] 2025-02-28 19:24:45,031 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
2025-02-28 19:24:45,033 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:24:45,034 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:24:45,034 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:24:45,035 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:24:45,035 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:24:45,036 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:24:45,036 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:24:45,036 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:24:45,036 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:24:45,036 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:24:45,036 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:24:45,036 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:24:45,037 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:24:45,037 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:24:45,037 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:24:45,037 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:24:45,037 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:24:45,038 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:24:45,038 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:24:45,038 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
2025-02-28 19:24:45,038 - root - INFO - [Telegram Bot] result = await self._request_wrapper(
2025-02-28 19:24:45,039 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
2025-02-28 19:24:45,039 - root - INFO - [Telegram Bot] raise Conflict(message)
2025-02-28 19:24:45,039 - root - INFO - [Telegram Bot] telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:24:58,750 - root - INFO - [Telegram Bot] 2025-02-28 19:24:58,750 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 409 Conflict"
2025-02-28 19:24:58,751 - root - INFO - [Telegram Bot] 2025-02-28 19:24:58,751 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:24:58,753 - root - INFO - [Telegram Bot] 2025-02-28 19:24:58,751 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
