2025-02-28 19:25:46,707 - root - INFO - [Telegram Bot] 2025-02-28 19:25:46,707 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
2025-02-28 19:25:46,712 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:25:46,712 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:25:46,713 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:25:46,713 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:25:46,713 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:25:46,713 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:25:46,715 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:25:46,715 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:25:46,715 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:25:46,715 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:25:46,716 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:25:46,718 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
2025-02-28 19:25:46,718 - root - INFO - [Telegram Bot] result = await self._request_wrapper(
2025-02-28 19:25:46,718 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
2025-02-28 19:25:46,718 - root - INFO - [Telegram Bot] raise Conflict(message)
2025-02-28 19:25:46,718 - root - INFO - [Telegram Bot] telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:25:47,163 - root - INFO - [Flask App] 2025-02-28 19:25:47,163 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:25:47,164 - root - INFO - [Flask App] 2025-02-28 19:25:47,163 - app - INFO -  „ »œ¡  ‘€Ì·  ÿ»Ìﬁ MetaBit KYC
2025-02-28 19:25:52,470 - root - INFO - [Flask App] 2025-02-28 19:25:52,470 - werkzeug - WARNING -  * Debugger is active!
2025-02-28 19:25:52,473 - root - INFO - [Flask App] 2025-02-28 19:25:52,473 - werkzeug - INFO -  * Debugger PIN: 535-157-907
2025-02-28 19:25:55,772 - root - INFO - [Telegram Bot] 2025-02-28 19:25:55,771 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 409 Conflict"
2025-02-28 19:25:55,774 - root - INFO - [Telegram Bot] 2025-02-28 19:25:55,772 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:25:55,774 - root - INFO - [Telegram Bot] 2025-02-28 19:25:55,772 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
2025-02-28 19:25:55,775 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:25:55,775 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:25:55,775 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:25:55,775 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:25:55,776 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:25:55,776 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:25:55,776 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:25:55,777 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:25:55,777 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:25:55,777 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:25:55,777 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:25:55,777 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:25:55,777 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:25:55,777 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:25:55,779 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:25:55,779 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:25:55,779 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:25:55,779 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:25:55,780 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:25:55,780 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
2025-02-28 19:25:55,780 - root - INFO - [Telegram Bot] result = await self._request_wrapper(
2025-02-28 19:25:55,780 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
2025-02-28 19:25:55,780 - root - INFO - [Telegram Bot] raise Conflict(message)
2025-02-28 19:25:55,780 - root - INFO - [Telegram Bot] telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:25:55,850 - root - INFO - [Flask App] 2025-02-28 19:25:55,850 - werkzeug - INFO - 127.0.0.1 - - [28/Feb/2025 19:25:55] "GET /api/check_status/KYC-20250228-FAB6XQII HTTP/1.1" 200 -
2025-02-28 19:25:59,461 - root - INFO - [Flask App] 2025-02-28 19:25:59,460 - werkzeug - INFO - 127.0.0.1 - - [28/Feb/2025 19:25:59] "GET /api/check_status/KYC-20250228-FAB6XQII HTTP/1.1" 200 -
2025-02-28 19:26:09,482 - root - INFO - [Telegram Bot] 2025-02-28 19:26:09,481 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8068331897:AAHa8V519tgNs7vFSEs9OdAyykx8yWH-Xx0/getUpdates "HTTP/1.1 409 Conflict"
2025-02-28 19:26:09,484 - root - INFO - [Telegram Bot] 2025-02-28 19:26:09,483 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-02-28 19:26:09,485 - root - INFO - [Telegram Bot] 2025-02-28 19:26:09,483 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
2025-02-28 19:26:09,486 - root - INFO - [Telegram Bot] Traceback (most recent call last):
2025-02-28 19:26:09,487 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
2025-02-28 19:26:09,488 - root - INFO - [Telegram Bot] if not await action_cb():
2025-02-28 19:26:09,489 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
2025-02-28 19:26:09,490 - root - INFO - [Telegram Bot] raise exc
2025-02-28 19:26:09,490 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
2025-02-28 19:26:09,491 - root - INFO - [Telegram Bot] updates = await self.bot.get_updates(
2025-02-28 19:26:09,491 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
2025-02-28 19:26:09,491 - root - INFO - [Telegram Bot] updates = await super().get_updates(
2025-02-28 19:26:09,491 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 525, in decorator
2025-02-28 19:26:09,492 - root - INFO - [Telegram Bot] result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
2025-02-28 19:26:09,492 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 3584, in get_updates
2025-02-28 19:26:09,492 - root - INFO - [Telegram Bot] await self._post(
2025-02-28 19:26:09,493 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 613, in _post
2025-02-28 19:26:09,493 - root - INFO - [Telegram Bot] return await self._do_post(
2025-02-28 19:26:09,493 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
2025-02-28 19:26:09,494 - root - INFO - [Telegram Bot] return await super()._do_post(
2025-02-28 19:26:09,494 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\_bot.py", line 641, in _do_post
2025-02-28 19:26:09,494 - root - INFO - [Telegram Bot] return await request.post(
2025-02-28 19:26:09,494 - root - INFO - [Telegram Bot] File "C:\Python310\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
